// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "development/libraries/rpc";
import { Codes } from "development/libraries/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const PlayerServicePort = 11;

export interface GetPlayerMetadataRequest {
}

export interface GetPlayerMetadataResponse {
    player?: PlayerMetadata;
}

export interface PatchPlayerMetadataRequest {
    player?: PlayerMetadata;
}

export interface PatchPlayerMetadataResponse {
}

export interface PlayerMetadata {
    hackingLevel?: number;
    portOpenersOwned?: number;
    strength?: number;
    defense?: number;
    dexterity?: number;
    agility?: number;
    charisma?: number;
    intelligence?: number;
    singularityAvailable?: boolean;
}

export interface PlayerServiceHandlers {
    GetPlayerMetadata: (req: GetPlayerMetadataRequest) => Promise<GetPlayerMetadataResponse> | GetPlayerMetadataResponse;
    PatchPlayerMetadata: (req: PatchPlayerMetadataRequest) => Promise<PatchPlayerMetadataResponse> | PatchPlayerMetadataResponse;
}

export function NewPlayerServiceClient(ns: NS, targetPort = PlayerServicePort) {
    return {
        GetPlayerMetadata: async (req: GetPlayerMetadataRequest, timeoutMs = 10000): Promise<rpc.RpcResponse<GetPlayerMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const envelope: rpc.RpcEnvelope<GetPlayerMetadataRequest> = { service: "PlayerService", method: "GetPlayerMetadata", replyPort, payload: req };

            const deadline = Date.now() + timeoutMs;

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), deadline);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.GetPlayerMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", deadline);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.GetPlayerMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetPlayerMetadataResponse>;
        },
        PatchPlayerMetadata: async (req: PatchPlayerMetadataRequest, timeoutMs = 10000): Promise<rpc.RpcResponse<PatchPlayerMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const envelope: rpc.RpcEnvelope<PatchPlayerMetadataRequest> = { service: "PlayerService", method: "PatchPlayerMetadata", replyPort, payload: req };

            const deadline = Date.now() + timeoutMs;

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), deadline);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.PatchPlayerMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", deadline);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.PatchPlayerMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PatchPlayerMetadataResponse>;
        },
    };
}

export function RegisterPlayerService(server: rpc.RpcServer, handlers: PlayerServiceHandlers) {
    server.registerService("PlayerService", handlers as unknown as Record<string, Function>);
}

