// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "development/libraries/rpc";
import { Codes } from "development/libraries/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const SchedulerServicePort = 12;

export enum Approach {
    HACK = 0,
    GROW_STATS = 1,
    CRIME = 2,
}

export interface GetSchedulerConfigRequest {
}

export interface GetSchedulerConfigResponse {
    config?: SchedulerConfig;
}

export interface PatchSchedulerConfigRequest {
    config?: SchedulerConfig;
}

export interface PatchSchedulerConfigResponse {
}

export interface SchedulerConfig {
    approach?: Approach;
    hackFraction?: number;
    spacingMs?: number;
    targetOverride?: string;
    homeFallbackHackingLevel?: number;
    homeReservedRamGb?: number;
}

export interface SchedulerServiceHandlers {
    GetSchedulerConfig: (req: GetSchedulerConfigRequest) => Promise<GetSchedulerConfigResponse> | GetSchedulerConfigResponse;
    PatchSchedulerConfig: (req: PatchSchedulerConfigRequest) => Promise<PatchSchedulerConfigResponse> | PatchSchedulerConfigResponse;
}

export function NewSchedulerServiceClient(ns: NS, targetPort = SchedulerServicePort) {
    return {
        GetSchedulerConfig: async (req: GetSchedulerConfigRequest, timeoutMs = 10000): Promise<rpc.RpcResponse<GetSchedulerConfigResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const envelope: rpc.RpcEnvelope<GetSchedulerConfigRequest> = { service: "SchedulerService", method: "GetSchedulerConfig", replyPort, payload: req };

            const deadline = Date.now() + timeoutMs;

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), deadline);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.GetSchedulerConfig could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", deadline);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.GetSchedulerConfig timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetSchedulerConfigResponse>;
        },
        PatchSchedulerConfig: async (req: PatchSchedulerConfigRequest, timeoutMs = 10000): Promise<rpc.RpcResponse<PatchSchedulerConfigResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const envelope: rpc.RpcEnvelope<PatchSchedulerConfigRequest> = { service: "SchedulerService", method: "PatchSchedulerConfig", replyPort, payload: req };

            const deadline = Date.now() + timeoutMs;

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), deadline);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.PatchSchedulerConfig could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", deadline);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.PatchSchedulerConfig timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PatchSchedulerConfigResponse>;
        },
    };
}

export function RegisterSchedulerService(server: rpc.RpcServer, handlers: SchedulerServiceHandlers) {
    server.registerService("SchedulerService", handlers as unknown as Record<string, Function>);
}

