// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import { RpcEnvelope, RpcResponse, RpcServer } from "development/libraries/rpc";

/** Keeps reply ports clear of low, statically-assigned service ports. */
const REPLY_PORT_OFFSET = 1000;

/** Port this service listens on, assigned by the generator's port registry. */
export const SupervisorPort = 10;

export interface UpdateMetadataRequest {
    server?: Metadata;
}

export interface ActionResponse {
    success?: boolean;
}

export interface PatchMetadataRequest {
    server?: Metadata;
}

export interface Metadata {
    hostname?: string;
    organization?: string;
    ip?: string;
    pathFromHome?: string;
    maxRam?: number;
    ramAvailable?: number;
    cpuCores?: number;
    purchasedByPlayer?: boolean;
    securityLevel?: number;
    minSecurityLevel?: number;
    growthMultiplier?: number;
    hacked?: boolean;
    backdoorInstalled?: boolean;
    hacking?: HackingData;
    moneyAvailable?: number;
    maxMoney?: number;
}

export interface HackingData {
    requirements?: HackingRequirements;
    ports?: HackingPorts;
}

export interface HackingRequirements {
    level?: number;
    ports?: number;
}

export interface HackingPorts {
    ssh?: boolean;
    ftp?: boolean;
    smtp?: boolean;
    http?: boolean;
    sql?: boolean;
}

export interface SupervisorHandlers {
    UpdateMetadata: (req: UpdateMetadataRequest) => Promise<ActionResponse> | ActionResponse;
    PatchMetadata: (req: PatchMetadataRequest) => Promise<ActionResponse> | ActionResponse;
}

export function NewClient(ns: NS, targetPort = SupervisorPort) {
    return {
        UpdateMetadata: async (req: UpdateMetadataRequest, timeoutMs = 10000): Promise<ActionResponse> => {
            const replyPort = ns.pid + REPLY_PORT_OFFSET;
            ns.clearPort(replyPort);
            const envelope: RpcEnvelope<UpdateMetadataRequest> = { service: "Supervisor", method: "UpdateMetadata", replyPort, payload: req };

            const start = Date.now();

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            while (!ns.tryWritePort(targetPort, JSON.stringify(envelope))) {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.UpdateMetadata could not be queued.`);
                await ns.sleep(10);
            }

            while (ns.peek(replyPort) === "NULL PORT DATA") {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.UpdateMetadata timed out.`);
                await ns.sleep(10);
            }

            // The server replies with JSON.stringify(response); parse it back.
            const res = JSON.parse(ns.readPort(replyPort) as string) as RpcResponse<ActionResponse>;
            if (!res.success) throw new Error(`[RPC Error] Supervisor.UpdateMetadata: ${res.error}`);
            return res.data!;
        },
        PatchMetadata: async (req: PatchMetadataRequest, timeoutMs = 10000): Promise<ActionResponse> => {
            const replyPort = ns.pid + REPLY_PORT_OFFSET;
            ns.clearPort(replyPort);
            const envelope: RpcEnvelope<PatchMetadataRequest> = { service: "Supervisor", method: "PatchMetadata", replyPort, payload: req };

            const start = Date.now();

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            while (!ns.tryWritePort(targetPort, JSON.stringify(envelope))) {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.PatchMetadata could not be queued.`);
                await ns.sleep(10);
            }

            while (ns.peek(replyPort) === "NULL PORT DATA") {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.PatchMetadata timed out.`);
                await ns.sleep(10);
            }

            // The server replies with JSON.stringify(response); parse it back.
            const res = JSON.parse(ns.readPort(replyPort) as string) as RpcResponse<ActionResponse>;
            if (!res.success) throw new Error(`[RPC Error] Supervisor.PatchMetadata: ${res.error}`);
            return res.data!;
        },
    };
}

export function RegisterSupervisor(server: RpcServer, handlers: SupervisorHandlers) {
    server.registerService("Supervisor", handlers as unknown as Record<string, Function>);
}
