// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import { RpcEnvelope, RpcResponse, RpcServer } from "development/libraries/rpc"; 

export interface UpdateMetadataRequest {
    server?: number;
}

export interface ActionResponse {
    success?: boolean;
}

export interface PatchMetadataRequest {
    server?: number;
}

export interface SupervisorHandlers {
    UpdateMetadata: (req: UpdateMetadataRequest) => Promise<ActionResponse> | ActionResponse;
    PatchMetadata: (req: PatchMetadataRequest) => Promise<ActionResponse> | ActionResponse;
}

export function NewClient(ns: NS, targetPort = 10) {
    return {
        UpdateMetadata: async (req: UpdateMetadataRequest, timeoutMs = 10000): Promise<ActionResponse> => {
            const replyPort = ns.pid;
            ns.clearPort(replyPort);
            const envelope: RpcEnvelope<UpdateMetadataRequest> = { service: "Supervisor", method: "UpdateMetadata", replyPort, payload: req };
            ns.writePort(targetPort, envelope);
            
            const start = Date.now();
            while (ns.peek(replyPort) === "NULL PORT DATA") {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.UpdateMetadata timed out.`);
                await ns.sleep(10);
            }
            
            const res = ns.readPort(replyPort) as RpcResponse<ActionResponse>;
            if (!res.success) throw new Error(`[RPC Error] Supervisor.UpdateMetadata: ${res.error}`);
            return res.data!;
        },
        PatchMetadata: async (req: PatchMetadataRequest, timeoutMs = 10000): Promise<ActionResponse> => {
            const replyPort = ns.pid;
            ns.clearPort(replyPort);
            const envelope: RpcEnvelope<PatchMetadataRequest> = { service: "Supervisor", method: "PatchMetadata", replyPort, payload: req };
            ns.writePort(targetPort, envelope);
            
            const start = Date.now();
            while (ns.peek(replyPort) === "NULL PORT DATA") {
                if (Date.now() - start > timeoutMs) throw new Error(`[RPC Timeout] Call to Supervisor.PatchMetadata timed out.`);
                await ns.sleep(10);
            }
            
            const res = ns.readPort(replyPort) as RpcResponse<ActionResponse>;
            if (!res.success) throw new Error(`[RPC Error] Supervisor.PatchMetadata: ${res.error}`);
            return res.data!;
        },
    };
}

export function RegisterSupervisor(server: RpcServer, handlers: SupervisorHandlers) {
    server.registerService("Supervisor", handlers as unknown as Record<string, Function>);
}