// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const PlayerServicePort = 11;

export interface GetPlayerMetadataRequest {
}

export interface GetPlayerMetadataResponse {
    player?: PlayerMetadata;
}

export interface PatchPlayerMetadataRequest {
    player?: PlayerMetadata;
}

export interface PatchPlayerMetadataResponse {
}

export interface PlayerMetadata {
    hackingLevel?: number;
    portOpenersOwned?: number;
    strength?: number;
    defense?: number;
    dexterity?: number;
    agility?: number;
    charisma?: number;
    intelligence?: number;
    singularityAvailable?: boolean;
    money?: number;
    gangAvailable?: boolean;
    hackingExp?: number;
    karma?: number;
}

export interface PlayerServiceHandlers {
    GetPlayerMetadata: (req: GetPlayerMetadataRequest, ctx?: rpc.CallContext) => Promise<GetPlayerMetadataResponse> | GetPlayerMetadataResponse;
    PatchPlayerMetadata: (req: PatchPlayerMetadataRequest, ctx?: rpc.CallContext) => Promise<PatchPlayerMetadataResponse> | PatchPlayerMetadataResponse;
}

export function NewPlayerServiceClient(ns: NS, targetPort = PlayerServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetPlayerMetadata: async (req: GetPlayerMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetPlayerMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetPlayerMetadataRequest> = { service: "PlayerService", method: "GetPlayerMetadata", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.GetPlayerMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.GetPlayerMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetPlayerMetadataResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        PatchPlayerMetadata: async (req: PatchPlayerMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PatchPlayerMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PatchPlayerMetadataRequest> = { service: "PlayerService", method: "PatchPlayerMetadata", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.PatchPlayerMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.PatchPlayerMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PatchPlayerMetadataResponse>;
        },
    };
}

export function RegisterPlayerService(server: rpc.RpcServer, handlers: PlayerServiceHandlers) {
    server.registerService("PlayerService", handlers as unknown as Record<string, Function>);
}

export type PlayerServiceClient = ReturnType<typeof NewPlayerServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses PlayerService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewPlayerServiceLocalClient(handlers: PlayerServiceHandlers): PlayerServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to PlayerService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetPlayerMetadata: (req: GetPlayerMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetPlayerMetadata", handlers.GetPlayerMetadata, req, deadline),
        PatchPlayerMetadata: (req: PatchPlayerMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("PatchPlayerMetadata", handlers.PatchPlayerMetadata, req, deadline),
    };
}

