// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const SchedulerServicePort = 12;

export enum Approach {
    HACK = 0,
    GROW_STATS = 1,
    CRIME = 2,
    STOCK_TARGETING = 3,
    AUGMENTS = 4,
    GANG = 5,
    FACTION_GRIND = 6,
    DAEDALUS = 7,
}

export interface GetSchedulerConfigRequest {
}

export interface GetSchedulerConfigResponse {
    config?: SchedulerConfig;
}

export interface PatchSchedulerConfigRequest {
    config?: SchedulerConfig;
}

export interface PatchSchedulerConfigResponse {
}

export interface SchedulerConfig {
    approach?: Approach;
    hackFraction?: number;
    spacingMs?: number;
    targetOverride?: string;
    homeFallbackHackingLevel?: number;
    homeReservedRamGb?: number;
    autoHackFraction?: boolean;
    targetUtilization?: number;
    maxHackFraction?: number;
}

export interface SchedulerServiceHandlers {
    GetSchedulerConfig: (req: GetSchedulerConfigRequest, ctx?: rpc.CallContext) => Promise<GetSchedulerConfigResponse> | GetSchedulerConfigResponse;
    PatchSchedulerConfig: (req: PatchSchedulerConfigRequest, ctx?: rpc.CallContext) => Promise<PatchSchedulerConfigResponse> | PatchSchedulerConfigResponse;
}

export function NewSchedulerServiceClient(ns: NS, targetPort = SchedulerServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetSchedulerConfig: async (req: GetSchedulerConfigRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetSchedulerConfigResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetSchedulerConfigRequest> = { service: "SchedulerService", method: "GetSchedulerConfig", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.GetSchedulerConfig could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.GetSchedulerConfig timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetSchedulerConfigResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        PatchSchedulerConfig: async (req: PatchSchedulerConfigRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PatchSchedulerConfigResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PatchSchedulerConfigRequest> = { service: "SchedulerService", method: "PatchSchedulerConfig", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.PatchSchedulerConfig could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.PatchSchedulerConfig timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PatchSchedulerConfigResponse>;
        },
    };
}

export function RegisterSchedulerService(server: rpc.RpcServer, handlers: SchedulerServiceHandlers) {
    server.registerService("SchedulerService", handlers as unknown as Record<string, Function>);
}

export type SchedulerServiceClient = ReturnType<typeof NewSchedulerServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses SchedulerService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewSchedulerServiceLocalClient(handlers: SchedulerServiceHandlers): SchedulerServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SchedulerService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetSchedulerConfig: (req: GetSchedulerConfigRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetSchedulerConfig", handlers.GetSchedulerConfig, req, deadline),
        PatchSchedulerConfig: (req: PatchSchedulerConfigRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("PatchSchedulerConfig", handlers.PatchSchedulerConfig, req, deadline),
    };
}

