// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const SupervisorServicePort = 10;

export enum ServerKind {
    NPC = 0,
    HOME = 1,
    HACKNET = 2,
    PURCHASED = 3,
}

export enum RootStatus {
    UNROOTABLE = 0,
    ROOTABLE = 1,
    ROOTED = 2,
}

export enum HackStatus {
    UNHACKABLE = 0,
    HACKABLE = 1,
}

export interface UpdateMetadataRequest {
    server?: Metadata;
}

export interface UpdateMetadataResponse {
}

export interface PatchMetadataRequest {
    server?: Metadata;
}

export interface PatchMetadataResponse {
}

export interface ListServersRequest {
    eligibleOnly?: boolean;
}

export interface ListServersResponse {
    servers?: Metadata[];
}

export interface Metadata {
    hostname?: string;
    organization?: string;
    ip?: string;
    pathFromHome?: string;
    maxRam?: number;
    ramAvailable?: number;
    cpuCores?: number;
    kind?: ServerKind;
    securityLevel?: number;
    minSecurityLevel?: number;
    growthMultiplier?: number;
    backdoorInstalled?: boolean;
    hacking?: HackingData;
    moneyAvailable?: number;
    maxMoney?: number;
    rootStatus?: RootStatus;
    hackStatus?: HackStatus;
}

export interface HackingData {
    requirements?: HackingRequirements;
    ports?: HackingPorts;
}

export interface HackingRequirements {
    level?: number;
    ports?: number;
}

export interface HackingPorts {
    ssh?: boolean;
    ftp?: boolean;
    smtp?: boolean;
    http?: boolean;
    sql?: boolean;
}

export interface SupervisorServiceHandlers {
    UpdateMetadata: (req: UpdateMetadataRequest, ctx?: rpc.CallContext) => Promise<UpdateMetadataResponse> | UpdateMetadataResponse;
    PatchMetadata: (req: PatchMetadataRequest, ctx?: rpc.CallContext) => Promise<PatchMetadataResponse> | PatchMetadataResponse;
    ListServers: (req: ListServersRequest, ctx?: rpc.CallContext) => Promise<ListServersResponse> | ListServersResponse;
}

export function NewSupervisorServiceClient(ns: NS, targetPort = SupervisorServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        UpdateMetadata: async (req: UpdateMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<UpdateMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<UpdateMetadataRequest> = { service: "SupervisorService", method: "UpdateMetadata", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.UpdateMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.UpdateMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<UpdateMetadataResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        PatchMetadata: async (req: PatchMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PatchMetadataResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PatchMetadataRequest> = { service: "SupervisorService", method: "PatchMetadata", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.PatchMetadata could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.PatchMetadata timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PatchMetadataResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        ListServers: async (req: ListServersRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<ListServersResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<ListServersRequest> = { service: "SupervisorService", method: "ListServers", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.ListServers could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.ListServers timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<ListServersResponse>;
        },
    };
}

export function RegisterSupervisorService(server: rpc.RpcServer, handlers: SupervisorServiceHandlers) {
    server.registerService("SupervisorService", handlers as unknown as Record<string, Function>);
}

export type SupervisorServiceClient = ReturnType<typeof NewSupervisorServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses SupervisorService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewSupervisorServiceLocalClient(handlers: SupervisorServiceHandlers): SupervisorServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to SupervisorService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        UpdateMetadata: (req: UpdateMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("UpdateMetadata", handlers.UpdateMetadata, req, deadline),
        PatchMetadata: (req: PatchMetadataRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("PatchMetadata", handlers.PatchMetadata, req, deadline),
        ListServers: (req: ListServersRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("ListServers", handlers.ListServers, req, deadline),
    };
}

