// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const StateServicePort = 13;

export interface ListRequest {
    prefixes?: string[];
    exclude?: string[];
}

export interface ListResponse {
    paths?: string[];
}

export interface GetManyRequest {
    paths?: string[];
}

export interface GetManyResponse {
    documents?: Document[];
}

export interface PutManyRequest {
    documents?: Document[];
}

export interface PutManyResponse {
    written?: number;
}

export interface Document {
    path?: string;
    content?: string;
    append?: boolean;
}

export interface StateServiceHandlers {
    List: (req: ListRequest, ctx?: rpc.CallContext) => Promise<ListResponse> | ListResponse;
    GetMany: (req: GetManyRequest, ctx?: rpc.CallContext) => Promise<GetManyResponse> | GetManyResponse;
    PutMany: (req: PutManyRequest, ctx?: rpc.CallContext) => Promise<PutManyResponse> | PutManyResponse;
}

export function NewStateServiceClient(ns: NS, targetPort = StateServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        List: async (req: ListRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<ListResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<ListRequest> = { service: "StateService", method: "List", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.List could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.List timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<ListResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetMany: async (req: GetManyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetManyResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetManyRequest> = { service: "StateService", method: "GetMany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.GetMany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.GetMany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetManyResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        PutMany: async (req: PutManyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PutManyResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PutManyRequest> = { service: "StateService", method: "PutMany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.PutMany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.PutMany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PutManyResponse>;
        },
    };
}

export function RegisterStateService(server: rpc.RpcServer, handlers: StateServiceHandlers) {
    server.registerService("StateService", handlers as unknown as Record<string, Function>);
}

export type StateServiceClient = ReturnType<typeof NewStateServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses StateService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewStateServiceLocalClient(handlers: StateServiceHandlers): StateServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StateService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        List: (req: ListRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("List", handlers.List, req, deadline),
        GetMany: (req: GetManyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetMany", handlers.GetMany, req, deadline),
        PutMany: (req: PutManyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("PutMany", handlers.PutMany, req, deadline),
    };
}

