// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { AugDetail } from "factions/rpc/faction_types";
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const AugDetailServicePort = 30;

export interface GetDetailsRequest {
    names?: string[];
}

export interface GetDetailsResponse {
    details?: AugDetail[];
}

export interface AugDetailServiceHandlers {
    GetDetails: (req: GetDetailsRequest, ctx?: rpc.CallContext) => Promise<GetDetailsResponse> | GetDetailsResponse;
}

export function NewAugDetailServiceClient(ns: NS, targetPort = AugDetailServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetDetails: async (req: GetDetailsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetDetailsResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetDetailsRequest> = { service: "AugDetailService", method: "GetDetails", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.GetDetails could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.GetDetails timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetDetailsResponse>;
        },
    };
}

export function RegisterAugDetailService(server: rpc.RpcServer, handlers: AugDetailServiceHandlers) {
    server.registerService("AugDetailService", handlers as unknown as Record<string, Function>);
}

export type AugDetailServiceClient = ReturnType<typeof NewAugDetailServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugDetailService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugDetailServiceLocalClient(handlers: AugDetailServiceHandlers): AugDetailServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetDetails: (req: GetDetailsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetDetails", handlers.GetDetails, req, deadline),
    };
}

