// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const AugBuyServicePort = 28;

export interface PurchaseRequest {
    faction?: string;
    augmentation?: string;
}

export interface PurchaseResponse {
    ok?: boolean;
}

export interface DonateRequest {
    faction?: string;
    amount?: number;
}

export interface DonateResponse {
    ok?: boolean;
}

export interface AugBuyServiceHandlers {
    Purchase: (req: PurchaseRequest, ctx?: rpc.CallContext) => Promise<PurchaseResponse> | PurchaseResponse;
    Donate: (req: DonateRequest, ctx?: rpc.CallContext) => Promise<DonateResponse> | DonateResponse;
}

export function NewAugBuyServiceClient(ns: NS, targetPort = AugBuyServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Purchase: async (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PurchaseResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PurchaseRequest> = { service: "AugBuyService", method: "Purchase", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Purchase could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Purchase timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PurchaseResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Donate: async (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<DonateResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<DonateRequest> = { service: "AugBuyService", method: "Donate", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Donate could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Donate timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<DonateResponse>;
        },
    };
}

export function RegisterAugBuyService(server: rpc.RpcServer, handlers: AugBuyServiceHandlers) {
    server.registerService("AugBuyService", handlers as unknown as Record<string, Function>);
}

export type AugBuyServiceClient = ReturnType<typeof NewAugBuyServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugBuyService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugBuyServiceLocalClient(handlers: AugBuyServiceHandlers): AugBuyServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Purchase: (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Purchase", handlers.Purchase, req, deadline),
        Donate: (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Donate", handlers.Donate, req, deadline),
    };
}

