// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const CrimeServicePort = 31;

export interface CommitCrimeRequest {
    crime?: string;
}

export interface CommitCrimeResponse {
    ok?: boolean;
}

export interface CrimeServiceHandlers {
    CommitCrime: (req: CommitCrimeRequest, ctx?: rpc.CallContext) => Promise<CommitCrimeResponse> | CommitCrimeResponse;
}

export function NewCrimeServiceClient(ns: NS, targetPort = CrimeServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        CommitCrime: async (req: CommitCrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<CommitCrimeResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CommitCrimeRequest> = { service: "CrimeService", method: "CommitCrime", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.CommitCrime could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.CommitCrime timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<CommitCrimeResponse>;
        },
    };
}

export function RegisterCrimeService(server: rpc.RpcServer, handlers: CrimeServiceHandlers) {
    server.registerService("CrimeService", handlers as unknown as Record<string, Function>);
}

export type CrimeServiceClient = ReturnType<typeof NewCrimeServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses CrimeService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewCrimeServiceLocalClient(handlers: CrimeServiceHandlers): CrimeServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        CommitCrime: (req: CommitCrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("CommitCrime", handlers.CommitCrime, req, deadline),
    };
}

