// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const FactionInfoServicePort = 14;

/** Port this service listens on, assigned by the generator's port registry. */
export const FactionWorkServicePort = 15;

/** Port this service listens on, assigned by the generator's port registry. */
export const CrimeServicePort = 16;

/** Port this service listens on, assigned by the generator's port registry. */
export const AugmentPurchaseServicePort = 17;

export interface InfoRequest {
    standingFactions?: string[];
    offerFactions?: string[];
    companies?: string[];
}

export interface InfoSnapshot {
    offers?: FactionOffer[];
    augmentations?: Augmentation[];
    standings?: Standing[];
    ownedWithQueued?: string[];
    installed?: string[];
    favorToDonate?: number;
    companyStandings?: CompanyStanding[];
}

export interface WorkRequest {
    requirementFactions?: string[];
    workTypeFactions?: string[];
}

export interface WorkSnapshot {
    invitations?: string[];
    requirements?: FactionRequirements[];
    currentWorkJson?: string;
    workTypes?: FactionWorkTypes[];
}

export interface FactionRequest {
    faction?: string;
}

export interface Done {
    ok?: boolean;
    detail?: string;
}

export interface FactionWorkRequest {
    faction?: string;
    workType?: string;
}

export interface CompanyRequest {
    company?: string;
    field?: string;
}

export interface JobReply {
    job?: string;
}

export interface TravelRequest {
    city?: string;
}

export interface GymRequest {
    location?: string;
    gymType?: string;
}

export interface Empty {
}

export interface StudyRequest {
    university?: string;
    course?: string;
}

export interface CrimeSnapshot {
    crimes?: CrimeInfo[];
}

export interface CrimeRequest {
    crime?: string;
}

export interface PurchaseSnapshot {
    homeRamCost?: number;
    positionsHeld?: number;
}

export interface PurchaseRequest {
    faction?: string;
    augmentation?: string;
}

export interface DonateRequest {
    faction?: string;
    amount?: number;
}

export interface HomeRamReply {
    costs?: number[];
    ramAfter?: number;
}

export interface InstallRequest {
    bootScript?: string;
}

export interface FactionOffer {
    faction?: string;
    augmentations?: string[];
}

export interface Augmentation {
    name?: string;
    price?: number;
    repReq?: number;
    prereqs?: string[];
    stats?: Stat[];
}

export interface Standing {
    faction?: string;
    rep?: number;
    favor?: number;
}

export interface CompanyStanding {
    company?: string;
    rep?: number;
}

export interface FactionRequirements {
    faction?: string;
    requirementsJson?: string;
}

export interface FactionWorkTypes {
    faction?: string;
    types?: string[];
}

export interface CrimeInfo {
    crime?: string;
    karma?: number;
    timeMs?: number;
    kills?: number;
    chance?: number;
}

export interface Stat {
    key?: string;
    value?: number;
}

export interface FactionInfoServiceHandlers {
    Snapshot: (req: InfoRequest, ctx?: rpc.CallContext) => Promise<InfoSnapshot> | InfoSnapshot;
}

export function NewFactionInfoServiceClient(ns: NS, targetPort = FactionInfoServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: InfoRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<InfoSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<InfoRequest> = { service: "FactionInfoService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionInfoService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionInfoService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<InfoSnapshot>;
        },
    };
}

export function RegisterFactionInfoService(server: rpc.RpcServer, handlers: FactionInfoServiceHandlers) {
    server.registerService("FactionInfoService", handlers as unknown as Record<string, Function>);
}

export type FactionInfoServiceClient = ReturnType<typeof NewFactionInfoServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses FactionInfoService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewFactionInfoServiceLocalClient(handlers: FactionInfoServiceHandlers): FactionInfoServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionInfoService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: InfoRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
    };
}

export interface FactionWorkServiceHandlers {
    Snapshot: (req: WorkRequest, ctx?: rpc.CallContext) => Promise<WorkSnapshot> | WorkSnapshot;
    Join: (req: FactionRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    WorkForFaction: (req: FactionWorkRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    ApplyToCompany: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<JobReply> | JobReply;
    WorkForCompany: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    QuitJob: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Travel: (req: TravelRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Gym: (req: GymRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Stop: (req: Empty, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Study: (req: StudyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewFactionWorkServiceClient(ns: NS, targetPort = FactionWorkServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: WorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<WorkSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<WorkRequest> = { service: "FactionWorkService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<WorkSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Join: async (req: FactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionRequest> = { service: "FactionWorkService", method: "Join", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Join could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Join timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForFaction: async (req: FactionWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionWorkRequest> = { service: "FactionWorkService", method: "WorkForFaction", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.WorkForFaction could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.WorkForFaction timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        ApplyToCompany: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<JobReply>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "FactionWorkService", method: "ApplyToCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.ApplyToCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.ApplyToCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<JobReply>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForCompany: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "FactionWorkService", method: "WorkForCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.WorkForCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.WorkForCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        QuitJob: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "FactionWorkService", method: "QuitJob", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.QuitJob could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.QuitJob timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Travel: async (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<TravelRequest> = { service: "FactionWorkService", method: "Travel", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Travel could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Travel timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Gym: async (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GymRequest> = { service: "FactionWorkService", method: "Gym", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Gym could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Gym timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Stop: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "FactionWorkService", method: "Stop", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Stop could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Stop timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Study: async (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<StudyRequest> = { service: "FactionWorkService", method: "Study", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Study could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.Study timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterFactionWorkService(server: rpc.RpcServer, handlers: FactionWorkServiceHandlers) {
    server.registerService("FactionWorkService", handlers as unknown as Record<string, Function>);
}

export type FactionWorkServiceClient = ReturnType<typeof NewFactionWorkServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses FactionWorkService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewFactionWorkServiceLocalClient(handlers: FactionWorkServiceHandlers): FactionWorkServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to FactionWorkService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: WorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        Join: (req: FactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Join", handlers.Join, req, deadline),
        WorkForFaction: (req: FactionWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForFaction", handlers.WorkForFaction, req, deadline),
        ApplyToCompany: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("ApplyToCompany", handlers.ApplyToCompany, req, deadline),
        WorkForCompany: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForCompany", handlers.WorkForCompany, req, deadline),
        QuitJob: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("QuitJob", handlers.QuitJob, req, deadline),
        Travel: (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Travel", handlers.Travel, req, deadline),
        Gym: (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Gym", handlers.Gym, req, deadline),
        Stop: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Stop", handlers.Stop, req, deadline),
        Study: (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Study", handlers.Study, req, deadline),
    };
}

export interface CrimeServiceHandlers {
    Snapshot: (req: Empty, ctx?: rpc.CallContext) => Promise<CrimeSnapshot> | CrimeSnapshot;
    Commit: (req: CrimeRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewCrimeServiceClient(ns: NS, targetPort = CrimeServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<CrimeSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "CrimeService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<CrimeSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Commit: async (req: CrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CrimeRequest> = { service: "CrimeService", method: "Commit", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Commit could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Commit timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterCrimeService(server: rpc.RpcServer, handlers: CrimeServiceHandlers) {
    server.registerService("CrimeService", handlers as unknown as Record<string, Function>);
}

export type CrimeServiceClient = ReturnType<typeof NewCrimeServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses CrimeService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewCrimeServiceLocalClient(handlers: CrimeServiceHandlers): CrimeServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        Commit: (req: CrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Commit", handlers.Commit, req, deadline),
    };
}

export interface AugmentPurchaseServiceHandlers {
    Snapshot: (req: Empty, ctx?: rpc.CallContext) => Promise<PurchaseSnapshot> | PurchaseSnapshot;
    Purchase: (req: PurchaseRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Donate: (req: DonateRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    UpgradeHomeRam: (req: Empty, ctx?: rpc.CallContext) => Promise<HomeRamReply> | HomeRamReply;
    Install: (req: InstallRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewAugmentPurchaseServiceClient(ns: NS, targetPort = AugmentPurchaseServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<PurchaseSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "AugmentPurchaseService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<PurchaseSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Purchase: async (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PurchaseRequest> = { service: "AugmentPurchaseService", method: "Purchase", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Purchase could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Purchase timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Donate: async (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<DonateRequest> = { service: "AugmentPurchaseService", method: "Donate", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Donate could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Donate timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        UpgradeHomeRam: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<HomeRamReply>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "AugmentPurchaseService", method: "UpgradeHomeRam", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.UpgradeHomeRam could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.UpgradeHomeRam timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<HomeRamReply>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Install: async (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<InstallRequest> = { service: "AugmentPurchaseService", method: "Install", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Install could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.Install timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterAugmentPurchaseService(server: rpc.RpcServer, handlers: AugmentPurchaseServiceHandlers) {
    server.registerService("AugmentPurchaseService", handlers as unknown as Record<string, Function>);
}

export type AugmentPurchaseServiceClient = ReturnType<typeof NewAugmentPurchaseServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugmentPurchaseService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugmentPurchaseServiceLocalClient(handlers: AugmentPurchaseServiceHandlers): AugmentPurchaseServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugmentPurchaseService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        Purchase: (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Purchase", handlers.Purchase, req, deadline),
        Donate: (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Donate", handlers.Donate, req, deadline),
        UpgradeHomeRam: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("UpgradeHomeRam", handlers.UpgradeHomeRam, req, deadline),
        Install: (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Install", handlers.Install, req, deadline),
    };
}

