// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const AugCatalogServicePort = 18;

/** Port this service listens on, assigned by the generator's port registry. */
export const AugDetailServicePort = 19;

/** Port this service listens on, assigned by the generator's port registry. */
export const StandingServicePort = 20;

/** Port this service listens on, assigned by the generator's port registry. */
export const InviteServicePort = 21;

/** Port this service listens on, assigned by the generator's port registry. */
export const WorkServicePort = 22;

/** Port this service listens on, assigned by the generator's port registry. */
export const JobServicePort = 23;

/** Port this service listens on, assigned by the generator's port registry. */
export const CrimeInfoServicePort = 24;

/** Port this service listens on, assigned by the generator's port registry. */
export const CrimeServicePort = 16;

/** Port this service listens on, assigned by the generator's port registry. */
export const AugBuyServicePort = 25;

/** Port this service listens on, assigned by the generator's port registry. */
export const InstallServicePort = 26;

/** Port this service listens on, assigned by the generator's port registry. */
export const HomeRamServicePort = 27;

export interface CatalogRequest {
    factions?: string[];
    extraNames?: string[];
}

export interface CatalogSnapshot {
    offers?: FactionOffer[];
    prices?: AugPrice[];
}

export interface NamesRequest {
    names?: string[];
}

export interface DetailSnapshot {
    details?: AugDetail[];
}

export interface StandingRequest {
    factions?: string[];
    companies?: string[];
}

export interface StandingSnapshot {
    standings?: Standing[];
    ownedWithQueued?: string[];
    installed?: string[];
    favorToDonate?: number;
    companyStandings?: CompanyStanding[];
}

export interface FactionsRequest {
    factions?: string[];
}

export interface InviteSnapshot {
    invitations?: string[];
    requirements?: FactionRequirements[];
}

export interface FactionRequest {
    faction?: string;
}

export interface Done {
    ok?: boolean;
    detail?: string;
}

export interface WorkSnapshot {
    currentWorkJson?: string;
    workTypes?: FactionWorkTypes[];
}

export interface FactionWorkRequest {
    faction?: string;
    workType?: string;
}

export interface TravelRequest {
    city?: string;
}

export interface GymRequest {
    location?: string;
    gymType?: string;
}

export interface StudyRequest {
    university?: string;
    course?: string;
}

export interface Empty {
}

export interface CompanyRequest {
    company?: string;
    field?: string;
}

export interface JobReply {
    job?: string;
}

export interface CrimeSnapshot {
    crimes?: CrimeInfo[];
}

export interface CrimeRequest {
    crime?: string;
}

export interface PurchaseRequest {
    faction?: string;
    augmentation?: string;
}

export interface DonateRequest {
    faction?: string;
    amount?: number;
}

export interface InstallSnapshot {
    positionsHeld?: number;
}

export interface InstallRequest {
    bootScript?: string;
}

export interface HomeRamReply {
    costs?: number[];
    ramAfter?: number;
}

export interface FactionOffer {
    faction?: string;
    augmentations?: string[];
}

export interface AugPrice {
    name?: string;
    price?: number;
    repReq?: number;
}

export interface AugDetail {
    name?: string;
    prereqs?: string[];
    stats?: Stat[];
}

export interface Standing {
    faction?: string;
    rep?: number;
    favor?: number;
}

export interface CompanyStanding {
    company?: string;
    rep?: number;
}

export interface FactionRequirements {
    faction?: string;
    requirementsJson?: string;
}

export interface FactionWorkTypes {
    faction?: string;
    types?: string[];
}

export interface CrimeInfo {
    crime?: string;
    karma?: number;
    timeMs?: number;
    kills?: number;
    chance?: number;
}

export interface Stat {
    key?: string;
    value?: number;
}

export interface AugCatalogServiceHandlers {
    Snapshot: (req: CatalogRequest, ctx?: rpc.CallContext) => Promise<CatalogSnapshot> | CatalogSnapshot;
}

export function NewAugCatalogServiceClient(ns: NS, targetPort = AugCatalogServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: CatalogRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<CatalogSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CatalogRequest> = { service: "AugCatalogService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugCatalogService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugCatalogService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<CatalogSnapshot>;
        },
    };
}

export function RegisterAugCatalogService(server: rpc.RpcServer, handlers: AugCatalogServiceHandlers) {
    server.registerService("AugCatalogService", handlers as unknown as Record<string, Function>);
}

export type AugCatalogServiceClient = ReturnType<typeof NewAugCatalogServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugCatalogService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugCatalogServiceLocalClient(handlers: AugCatalogServiceHandlers): AugCatalogServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugCatalogService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: CatalogRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
    };
}

export interface AugDetailServiceHandlers {
    Snapshot: (req: NamesRequest, ctx?: rpc.CallContext) => Promise<DetailSnapshot> | DetailSnapshot;
}

export function NewAugDetailServiceClient(ns: NS, targetPort = AugDetailServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: NamesRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<DetailSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<NamesRequest> = { service: "AugDetailService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<DetailSnapshot>;
        },
    };
}

export function RegisterAugDetailService(server: rpc.RpcServer, handlers: AugDetailServiceHandlers) {
    server.registerService("AugDetailService", handlers as unknown as Record<string, Function>);
}

export type AugDetailServiceClient = ReturnType<typeof NewAugDetailServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugDetailService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugDetailServiceLocalClient(handlers: AugDetailServiceHandlers): AugDetailServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugDetailService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: NamesRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
    };
}

export interface StandingServiceHandlers {
    Snapshot: (req: StandingRequest, ctx?: rpc.CallContext) => Promise<StandingSnapshot> | StandingSnapshot;
}

export function NewStandingServiceClient(ns: NS, targetPort = StandingServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: StandingRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<StandingSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<StandingRequest> = { service: "StandingService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StandingService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StandingService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<StandingSnapshot>;
        },
    };
}

export function RegisterStandingService(server: rpc.RpcServer, handlers: StandingServiceHandlers) {
    server.registerService("StandingService", handlers as unknown as Record<string, Function>);
}

export type StandingServiceClient = ReturnType<typeof NewStandingServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses StandingService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewStandingServiceLocalClient(handlers: StandingServiceHandlers): StandingServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to StandingService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: StandingRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
    };
}

export interface InviteServiceHandlers {
    Snapshot: (req: FactionsRequest, ctx?: rpc.CallContext) => Promise<InviteSnapshot> | InviteSnapshot;
    Join: (req: FactionRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewInviteServiceClient(ns: NS, targetPort = InviteServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: FactionsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<InviteSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionsRequest> = { service: "InviteService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<InviteSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Join: async (req: FactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionRequest> = { service: "InviteService", method: "Join", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Join could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Join timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterInviteService(server: rpc.RpcServer, handlers: InviteServiceHandlers) {
    server.registerService("InviteService", handlers as unknown as Record<string, Function>);
}

export type InviteServiceClient = ReturnType<typeof NewInviteServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses InviteService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewInviteServiceLocalClient(handlers: InviteServiceHandlers): InviteServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: FactionsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        Join: (req: FactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Join", handlers.Join, req, deadline),
    };
}

export interface WorkServiceHandlers {
    Snapshot: (req: FactionsRequest, ctx?: rpc.CallContext) => Promise<WorkSnapshot> | WorkSnapshot;
    WorkForFaction: (req: FactionWorkRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Travel: (req: TravelRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Gym: (req: GymRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Study: (req: StudyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Stop: (req: Empty, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewWorkServiceClient(ns: NS, targetPort = WorkServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: FactionsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<WorkSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionsRequest> = { service: "WorkService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<WorkSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForFaction: async (req: FactionWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<FactionWorkRequest> = { service: "WorkService", method: "WorkForFaction", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.WorkForFaction could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.WorkForFaction timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Travel: async (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<TravelRequest> = { service: "WorkService", method: "Travel", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Travel could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Travel timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Gym: async (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GymRequest> = { service: "WorkService", method: "Gym", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Gym could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Gym timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Study: async (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<StudyRequest> = { service: "WorkService", method: "Study", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Study could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Study timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Stop: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "WorkService", method: "Stop", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Stop could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Stop timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterWorkService(server: rpc.RpcServer, handlers: WorkServiceHandlers) {
    server.registerService("WorkService", handlers as unknown as Record<string, Function>);
}

export type WorkServiceClient = ReturnType<typeof NewWorkServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses WorkService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewWorkServiceLocalClient(handlers: WorkServiceHandlers): WorkServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: FactionsRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        WorkForFaction: (req: FactionWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForFaction", handlers.WorkForFaction, req, deadline),
        Travel: (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Travel", handlers.Travel, req, deadline),
        Gym: (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Gym", handlers.Gym, req, deadline),
        Study: (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Study", handlers.Study, req, deadline),
        Stop: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Stop", handlers.Stop, req, deadline),
    };
}

export interface JobServiceHandlers {
    ApplyToCompany: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<JobReply> | JobReply;
    WorkForCompany: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    QuitJob: (req: CompanyRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewJobServiceClient(ns: NS, targetPort = JobServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        ApplyToCompany: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<JobReply>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "JobService", method: "ApplyToCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.ApplyToCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.ApplyToCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<JobReply>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForCompany: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "JobService", method: "WorkForCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.WorkForCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.WorkForCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        QuitJob: async (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CompanyRequest> = { service: "JobService", method: "QuitJob", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.QuitJob could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.QuitJob timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterJobService(server: rpc.RpcServer, handlers: JobServiceHandlers) {
    server.registerService("JobService", handlers as unknown as Record<string, Function>);
}

export type JobServiceClient = ReturnType<typeof NewJobServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses JobService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewJobServiceLocalClient(handlers: JobServiceHandlers): JobServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        ApplyToCompany: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("ApplyToCompany", handlers.ApplyToCompany, req, deadline),
        WorkForCompany: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForCompany", handlers.WorkForCompany, req, deadline),
        QuitJob: (req: CompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("QuitJob", handlers.QuitJob, req, deadline),
    };
}

export interface CrimeInfoServiceHandlers {
    Snapshot: (req: Empty, ctx?: rpc.CallContext) => Promise<CrimeSnapshot> | CrimeSnapshot;
}

export function NewCrimeInfoServiceClient(ns: NS, targetPort = CrimeInfoServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<CrimeSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "CrimeInfoService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeInfoService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeInfoService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<CrimeSnapshot>;
        },
    };
}

export function RegisterCrimeInfoService(server: rpc.RpcServer, handlers: CrimeInfoServiceHandlers) {
    server.registerService("CrimeInfoService", handlers as unknown as Record<string, Function>);
}

export type CrimeInfoServiceClient = ReturnType<typeof NewCrimeInfoServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses CrimeInfoService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewCrimeInfoServiceLocalClient(handlers: CrimeInfoServiceHandlers): CrimeInfoServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeInfoService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
    };
}

export interface CrimeServiceHandlers {
    Commit: (req: CrimeRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewCrimeServiceClient(ns: NS, targetPort = CrimeServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Commit: async (req: CrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<CrimeRequest> = { service: "CrimeService", method: "Commit", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Commit could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.Commit timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterCrimeService(server: rpc.RpcServer, handlers: CrimeServiceHandlers) {
    server.registerService("CrimeService", handlers as unknown as Record<string, Function>);
}

export type CrimeServiceClient = ReturnType<typeof NewCrimeServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses CrimeService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewCrimeServiceLocalClient(handlers: CrimeServiceHandlers): CrimeServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to CrimeService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Commit: (req: CrimeRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Commit", handlers.Commit, req, deadline),
    };
}

export interface AugBuyServiceHandlers {
    Purchase: (req: PurchaseRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
    Donate: (req: DonateRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewAugBuyServiceClient(ns: NS, targetPort = AugBuyServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Purchase: async (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<PurchaseRequest> = { service: "AugBuyService", method: "Purchase", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Purchase could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Purchase timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Donate: async (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<DonateRequest> = { service: "AugBuyService", method: "Donate", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Donate could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.Donate timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterAugBuyService(server: rpc.RpcServer, handlers: AugBuyServiceHandlers) {
    server.registerService("AugBuyService", handlers as unknown as Record<string, Function>);
}

export type AugBuyServiceClient = ReturnType<typeof NewAugBuyServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses AugBuyService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewAugBuyServiceLocalClient(handlers: AugBuyServiceHandlers): AugBuyServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to AugBuyService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Purchase: (req: PurchaseRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Purchase", handlers.Purchase, req, deadline),
        Donate: (req: DonateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Donate", handlers.Donate, req, deadline),
    };
}

export interface InstallServiceHandlers {
    Snapshot: (req: Empty, ctx?: rpc.CallContext) => Promise<InstallSnapshot> | InstallSnapshot;
    Install: (req: InstallRequest, ctx?: rpc.CallContext) => Promise<Done> | Done;
}

export function NewInstallServiceClient(ns: NS, targetPort = InstallServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Snapshot: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<InstallSnapshot>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "InstallService", method: "Snapshot", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Snapshot could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Snapshot timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<InstallSnapshot>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Install: async (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<Done>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<InstallRequest> = { service: "InstallService", method: "Install", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Install could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Install timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<Done>;
        },
    };
}

export function RegisterInstallService(server: rpc.RpcServer, handlers: InstallServiceHandlers) {
    server.registerService("InstallService", handlers as unknown as Record<string, Function>);
}

export type InstallServiceClient = ReturnType<typeof NewInstallServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses InstallService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewInstallServiceLocalClient(handlers: InstallServiceHandlers): InstallServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        Snapshot: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Snapshot", handlers.Snapshot, req, deadline),
        Install: (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Install", handlers.Install, req, deadline),
    };
}

export interface HomeRamServiceHandlers {
    UpgradeHomeRam: (req: Empty, ctx?: rpc.CallContext) => Promise<HomeRamReply> | HomeRamReply;
}

export function NewHomeRamServiceClient(ns: NS, targetPort = HomeRamServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        UpgradeHomeRam: async (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<HomeRamReply>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<Empty> = { service: "HomeRamService", method: "UpgradeHomeRam", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.UpgradeHomeRam could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.UpgradeHomeRam timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<HomeRamReply>;
        },
    };
}

export function RegisterHomeRamService(server: rpc.RpcServer, handlers: HomeRamServiceHandlers) {
    server.registerService("HomeRamService", handlers as unknown as Record<string, Function>);
}

export type HomeRamServiceClient = ReturnType<typeof NewHomeRamServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses HomeRamService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewHomeRamServiceLocalClient(handlers: HomeRamServiceHandlers): HomeRamServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        UpgradeHomeRam: (req: Empty, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("UpgradeHomeRam", handlers.UpgradeHomeRam, req, deadline),
    };
}

