// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
export interface Stat {
    key?: string;
    value?: number;
}

export interface FactionOffer {
    faction?: string;
    augmentations?: string[];
}

export interface AugPrice {
    name?: string;
    price?: number;
    repReq?: number;
}

export interface AugDetail {
    name?: string;
    prereqs?: string[];
    stats?: Stat[];
}

export interface Standing {
    faction?: string;
    rep?: number;
    favor?: number;
}

export interface CompanyStanding {
    company?: string;
    rep?: number;
}

export interface FactionRequirements {
    faction?: string;
    requirementsJson?: string;
}

export interface FactionWorkTypes {
    faction?: string;
    types?: string[];
}

export interface CrimeInfo {
    crime?: string;
    karma?: number;
    timeMs?: number;
    kills?: number;
    chance?: number;
}

