// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const HomeRamServicePort = 33;

export interface UpgradeHomeRamRequest {
}

export interface UpgradeHomeRamResponse {
    costs?: number[];
    ramAfter?: number;
}

export interface HomeRamServiceHandlers {
    UpgradeHomeRam: (req: UpgradeHomeRamRequest, ctx?: rpc.CallContext) => Promise<UpgradeHomeRamResponse> | UpgradeHomeRamResponse;
}

export function NewHomeRamServiceClient(ns: NS, targetPort = HomeRamServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        UpgradeHomeRam: async (req: UpgradeHomeRamRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<UpgradeHomeRamResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<UpgradeHomeRamRequest> = { service: "HomeRamService", method: "UpgradeHomeRam", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.UpgradeHomeRam could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.UpgradeHomeRam timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<UpgradeHomeRamResponse>;
        },
    };
}

export function RegisterHomeRamService(server: rpc.RpcServer, handlers: HomeRamServiceHandlers) {
    server.registerService("HomeRamService", handlers as unknown as Record<string, Function>);
}

export type HomeRamServiceClient = ReturnType<typeof NewHomeRamServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses HomeRamService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewHomeRamServiceLocalClient(handlers: HomeRamServiceHandlers): HomeRamServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to HomeRamService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        UpgradeHomeRam: (req: UpgradeHomeRamRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("UpgradeHomeRam", handlers.UpgradeHomeRam, req, deadline),
    };
}

