// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const InstallServicePort = 34;

export interface GetInstallStateRequest {
}

export interface GetInstallStateResponse {
    positionsHeld?: number;
}

export interface InstallRequest {
    bootScript?: string;
}

export interface InstallResponse {
    ok?: boolean;
}

export interface InstallServiceHandlers {
    GetInstallState: (req: GetInstallStateRequest, ctx?: rpc.CallContext) => Promise<GetInstallStateResponse> | GetInstallStateResponse;
    Install: (req: InstallRequest, ctx?: rpc.CallContext) => Promise<InstallResponse> | InstallResponse;
}

export function NewInstallServiceClient(ns: NS, targetPort = InstallServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetInstallState: async (req: GetInstallStateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetInstallStateResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetInstallStateRequest> = { service: "InstallService", method: "GetInstallState", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.GetInstallState could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.GetInstallState timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetInstallStateResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Install: async (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<InstallResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<InstallRequest> = { service: "InstallService", method: "Install", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Install could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.Install timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<InstallResponse>;
        },
    };
}

export function RegisterInstallService(server: rpc.RpcServer, handlers: InstallServiceHandlers) {
    server.registerService("InstallService", handlers as unknown as Record<string, Function>);
}

export type InstallServiceClient = ReturnType<typeof NewInstallServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses InstallService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewInstallServiceLocalClient(handlers: InstallServiceHandlers): InstallServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InstallService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetInstallState: (req: GetInstallStateRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetInstallState", handlers.GetInstallState, req, deadline),
        Install: (req: InstallRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Install", handlers.Install, req, deadline),
    };
}

