// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { FactionRequirements } from "factions/rpc/faction_types";
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const InviteServicePort = 35;

export interface GetInvitesRequest {
    factions?: string[];
}

export interface GetInvitesResponse {
    invitations?: string[];
    requirements?: FactionRequirements[];
}

export interface JoinRequest {
    faction?: string;
}

export interface JoinResponse {
    ok?: boolean;
}

export interface InviteServiceHandlers {
    GetInvites: (req: GetInvitesRequest, ctx?: rpc.CallContext) => Promise<GetInvitesResponse> | GetInvitesResponse;
    Join: (req: JoinRequest, ctx?: rpc.CallContext) => Promise<JoinResponse> | JoinResponse;
}

export function NewInviteServiceClient(ns: NS, targetPort = InviteServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetInvites: async (req: GetInvitesRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetInvitesResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetInvitesRequest> = { service: "InviteService", method: "GetInvites", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.GetInvites could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.GetInvites timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetInvitesResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Join: async (req: JoinRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<JoinResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<JoinRequest> = { service: "InviteService", method: "Join", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Join could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.Join timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<JoinResponse>;
        },
    };
}

export function RegisterInviteService(server: rpc.RpcServer, handlers: InviteServiceHandlers) {
    server.registerService("InviteService", handlers as unknown as Record<string, Function>);
}

export type InviteServiceClient = ReturnType<typeof NewInviteServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses InviteService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewInviteServiceLocalClient(handlers: InviteServiceHandlers): InviteServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to InviteService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetInvites: (req: GetInvitesRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetInvites", handlers.GetInvites, req, deadline),
        Join: (req: JoinRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Join", handlers.Join, req, deadline),
    };
}

