// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const JobServicePort = 36;

export interface ApplyToCompanyRequest {
    company?: string;
    field?: string;
}

export interface ApplyToCompanyResponse {
    job?: string;
}

export interface WorkForCompanyRequest {
    company?: string;
}

export interface WorkForCompanyResponse {
    ok?: boolean;
}

export interface QuitJobRequest {
    company?: string;
}

export interface QuitJobResponse {
    ok?: boolean;
}

export interface JobServiceHandlers {
    ApplyToCompany: (req: ApplyToCompanyRequest, ctx?: rpc.CallContext) => Promise<ApplyToCompanyResponse> | ApplyToCompanyResponse;
    WorkForCompany: (req: WorkForCompanyRequest, ctx?: rpc.CallContext) => Promise<WorkForCompanyResponse> | WorkForCompanyResponse;
    QuitJob: (req: QuitJobRequest, ctx?: rpc.CallContext) => Promise<QuitJobResponse> | QuitJobResponse;
}

export function NewJobServiceClient(ns: NS, targetPort = JobServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        ApplyToCompany: async (req: ApplyToCompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<ApplyToCompanyResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<ApplyToCompanyRequest> = { service: "JobService", method: "ApplyToCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.ApplyToCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.ApplyToCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<ApplyToCompanyResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForCompany: async (req: WorkForCompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<WorkForCompanyResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<WorkForCompanyRequest> = { service: "JobService", method: "WorkForCompany", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.WorkForCompany could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.WorkForCompany timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<WorkForCompanyResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        QuitJob: async (req: QuitJobRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<QuitJobResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<QuitJobRequest> = { service: "JobService", method: "QuitJob", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.QuitJob could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.QuitJob timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<QuitJobResponse>;
        },
    };
}

export function RegisterJobService(server: rpc.RpcServer, handlers: JobServiceHandlers) {
    server.registerService("JobService", handlers as unknown as Record<string, Function>);
}

export type JobServiceClient = ReturnType<typeof NewJobServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses JobService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewJobServiceLocalClient(handlers: JobServiceHandlers): JobServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to JobService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        ApplyToCompany: (req: ApplyToCompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("ApplyToCompany", handlers.ApplyToCompany, req, deadline),
        WorkForCompany: (req: WorkForCompanyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForCompany", handlers.WorkForCompany, req, deadline),
        QuitJob: (req: QuitJobRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("QuitJob", handlers.QuitJob, req, deadline),
    };
}

