// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { FactionWorkTypes } from "factions/rpc/faction_types";
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { Deadline, expired, toDeadline } from "system/deadline";
import { Codes } from "system/rpc/status";

/** Port this service listens on, assigned by the generator's port registry. */
export const WorkServicePort = 38;

export interface GetWorkRequest {
    factions?: string[];
}

export interface GetWorkResponse {
    currentWorkJson?: string;
    workTypes?: FactionWorkTypes[];
}

export interface WorkForFactionRequest {
    faction?: string;
    workType?: string;
}

export interface WorkForFactionResponse {
    ok?: boolean;
}

export interface TravelRequest {
    city?: string;
}

export interface TravelResponse {
    ok?: boolean;
}

export interface GymRequest {
    location?: string;
    gymType?: string;
}

export interface GymResponse {
    ok?: boolean;
}

export interface StudyRequest {
    university?: string;
    course?: string;
}

export interface StudyResponse {
    ok?: boolean;
}

export interface StopRequest {
}

export interface StopResponse {
    ok?: boolean;
}

export interface WorkServiceHandlers {
    GetWork: (req: GetWorkRequest, ctx?: rpc.CallContext) => Promise<GetWorkResponse> | GetWorkResponse;
    WorkForFaction: (req: WorkForFactionRequest, ctx?: rpc.CallContext) => Promise<WorkForFactionResponse> | WorkForFactionResponse;
    Travel: (req: TravelRequest, ctx?: rpc.CallContext) => Promise<TravelResponse> | TravelResponse;
    Gym: (req: GymRequest, ctx?: rpc.CallContext) => Promise<GymResponse> | GymResponse;
    Study: (req: StudyRequest, ctx?: rpc.CallContext) => Promise<StudyResponse> | StudyResponse;
    Stop: (req: StopRequest, ctx?: rpc.CallContext) => Promise<StopResponse> | StopResponse;
}

export function NewWorkServiceClient(ns: NS, targetPort = WorkServicePort) {
    return {
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        GetWork: async (req: GetWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GetWorkResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GetWorkRequest> = { service: "WorkService", method: "GetWork", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.GetWork could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.GetWork timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GetWorkResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        WorkForFaction: async (req: WorkForFactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<WorkForFactionResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<WorkForFactionRequest> = { service: "WorkService", method: "WorkForFaction", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.WorkForFaction could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.WorkForFaction timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<WorkForFactionResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Travel: async (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<TravelResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<TravelRequest> = { service: "WorkService", method: "Travel", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Travel could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Travel timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<TravelResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Gym: async (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<GymResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<GymRequest> = { service: "WorkService", method: "Gym", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Gym could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Gym timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<GymResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Study: async (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<StudyResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<StudyRequest> = { service: "WorkService", method: "Study", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Study could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Study timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<StudyResponse>;
        },
        // `deadline`: when the caller needs the answer by (system/deadline.ts) -
        // a Deadline passed down from its own caller, or milliseconds from now.
        Stop: async (req: StopRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS): Promise<rpc.RpcResponse<StopResponse>> => {
            const replyPort = rpc.nextReplyPort(ns);
            ns.clearPort(replyPort);
            const callDeadline = toDeadline(deadline);
            const envelope: rpc.RpcEnvelope<StopRequest> = { service: "WorkService", method: "Stop", replyPort, payload: req, deadline: callDeadline.at };

            // Ports hold a bounded number of entries; writePort silently evicts on overflow.
            const queued = await rpc.pollWithBackoff(ns, () => ns.tryWritePort(targetPort, JSON.stringify(envelope)), callDeadline.at);
            if (!queued) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Stop could not be queued.` };
            }

            const replied = await rpc.pollWithBackoff(ns, () => ns.peek(replyPort) !== "NULL PORT DATA", callDeadline.at);
            if (!replied) {
                return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.Stop timed out.` };
            }

            // The server replies with JSON.stringify(response); parse it back.
            return JSON.parse(ns.readPort(replyPort) as string) as rpc.RpcResponse<StopResponse>;
        },
    };
}

export function RegisterWorkService(server: rpc.RpcServer, handlers: WorkServiceHandlers) {
    server.registerService("WorkService", handlers as unknown as Record<string, Function>);
}

export type WorkServiceClient = ReturnType<typeof NewWorkServiceClient>;

/**
 * The same client, calling `handlers` in-process instead of over a port -
 * for tests of anything that uses WorkService: no ports or game needed, same
 * RpcResponse results, deadlines and error statuses as the real thing.
 */
export function NewWorkServiceLocalClient(handlers: WorkServiceHandlers): WorkServiceClient {
    const call = async <Req, Res>(method: string, fn: (req: Req, ctx?: rpc.CallContext) => Promise<Res> | Res, req: Req, deadline: Deadline | number): Promise<rpc.RpcResponse<Res>> => {
        const callDeadline = toDeadline(deadline);
        if (expired(callDeadline)) return { status: Codes.DEADLINE_EXCEEDED, error: `Call to WorkService.${method} arrived after its deadline.` };
        try {
            return { status: Codes.OK, data: await fn(req, { deadline: callDeadline }) };
        } catch (err: any) {
            return { status: err instanceof rpc.RpcError ? err.status : Codes.INTERNAL, error: err?.message || String(err) };
        }
    };
    return {
        GetWork: (req: GetWorkRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("GetWork", handlers.GetWork, req, deadline),
        WorkForFaction: (req: WorkForFactionRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("WorkForFaction", handlers.WorkForFaction, req, deadline),
        Travel: (req: TravelRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Travel", handlers.Travel, req, deadline),
        Gym: (req: GymRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Gym", handlers.Gym, req, deadline),
        Study: (req: StudyRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Study", handlers.Study, req, deadline),
        Stop: (req: StopRequest, deadline: Deadline | number = rpc.DEFAULT_TIMEOUT_MS) => call("Stop", handlers.Stop, req, deadline),
    };
}

