// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { AugBuyServicePort, RegisterAugBuyService } from "factions/rpc/faction_services";
import { createAugBuyHandlers } from "factions/services/aug_buy_handlers";

/** Serves AugBuyService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, AugBuyServicePort);
  RegisterAugBuyService(server, createAugBuyHandlers(ns));
  await server.Serve();
}
