// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { AugDetailServicePort, RegisterAugDetailService } from "factions/rpc/faction_services";
import { createAugDetailHandlers } from "factions/services/aug_detail_handlers";

/** Serves AugDetailService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, AugDetailServicePort);
  RegisterAugDetailService(server, createAugDetailHandlers(ns));
  await server.Serve();
}
