// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { AugCatalogServicePort, RegisterAugCatalogService } from "factions/rpc/faction_services";
import { createAugCatalogHandlers } from "factions/services/aug_catalog_handlers";

/** Serves AugCatalogService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, AugCatalogServicePort);
  RegisterAugCatalogService(server, createAugCatalogHandlers(ns));
  await server.Serve();
}
