// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { CrimeServicePort, RegisterCrimeService } from "factions/rpc/faction_services";
import { createCrimeHandlers } from "factions/services/crime_handlers";

/** Serves CrimeService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, CrimeServicePort);
  RegisterCrimeService(server, createCrimeHandlers(ns));
  await server.Serve();
}
