// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { CrimeInfoServicePort, RegisterCrimeInfoService } from "factions/rpc/faction_services";
import { createCrimeInfoHandlers } from "factions/services/crime_info_handlers";

/** Serves CrimeInfoService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, CrimeInfoServicePort);
  RegisterCrimeInfoService(server, createCrimeInfoHandlers(ns));
  await server.Serve();
}
