// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
/** Every generated service main in factions/services - what boot.ts places. */
export const FACTIONS_SERVICE_SCRIPTS = [
  "factions/services/aug_buy_service.js",
  "factions/services/aug_catalog_service.js",
  "factions/services/aug_detail_service.js",
  "factions/services/crime_info_service.js",
  "factions/services/crime_service.js",
  "factions/services/home_ram_service.js",
  "factions/services/install_service.js",
  "factions/services/invite_service.js",
  "factions/services/job_service.js",
  "factions/services/standing_service.js",
  "factions/services/work_service.js"
];
