// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
/** faction_services's service scripts, in proto order - what boot.ts places. */
export const FACTION_SERVICES_SCRIPTS = [
  "factions/services/aug_catalog_service.js",
  "factions/services/aug_detail_service.js",
  "factions/services/standing_service.js",
  "factions/services/invite_service.js",
  "factions/services/work_service.js",
  "factions/services/job_service.js",
  "factions/services/crime_info_service.js",
  "factions/services/crime_service.js",
  "factions/services/aug_buy_service.js",
  "factions/services/install_service.js",
  "factions/services/home_ram_service.js"
];
