// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { HomeRamServicePort, RegisterHomeRamService } from "factions/rpc/home_ram";
import { createHomeRamHandlers } from "factions/services/home_ram_handlers";

/** Serves HomeRamService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, HomeRamServicePort);
  RegisterHomeRamService(server, createHomeRamHandlers(ns));
  await server.Serve();
}
