// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { InstallServicePort, RegisterInstallService } from "factions/rpc/install";
import { createInstallHandlers } from "factions/services/install_handlers";

/** Serves InstallService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, InstallServicePort);
  RegisterInstallService(server, createInstallHandlers(ns));
  await server.Serve();
}
