// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { InviteServicePort, RegisterInviteService } from "factions/rpc/invite";
import { createInviteHandlers } from "factions/services/invite_handlers";

/** Serves InviteService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, InviteServicePort);
  RegisterInviteService(server, createInviteHandlers(ns));
  await server.Serve();
}
