// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { JobServicePort, RegisterJobService } from "factions/rpc/job";
import { createJobHandlers } from "factions/services/job_handlers";

/** Serves JobService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, JobServicePort);
  RegisterJobService(server, createJobHandlers(ns));
  await server.Serve();
}
