// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { StandingServicePort, RegisterStandingService } from "factions/rpc/standing";
import { createStandingHandlers } from "factions/services/standing_handlers";

/** Serves StandingService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, StandingServicePort);
  RegisterStandingService(server, createStandingHandlers(ns));
  await server.Serve();
}
