// AUTO-GENERATED BY PROTO-GENERATOR - DO NOT EDIT
import { NS } from "@ns";
import * as rpc from "system/rpc/rpc";
import { WorkServicePort, RegisterWorkService } from "factions/rpc/faction_services";
import { createWorkHandlers } from "factions/services/work_handlers";

/** Serves WorkService on its port (any server - ports are global). */
export async function main(ns: NS): Promise<void> {
  ns.disableLog("ALL");
  const server = rpc.NewServer(ns, WorkServicePort);
  RegisterWorkService(server, createWorkHandlers(ns));
  await server.Serve();
}
